/************* Code Composer V1 Project Data ********************
  The following section contains data generated by Code Composer
  to store project information like build options, source filenames
  and dependencies.

[command filename]
..\SOURCE\pdi.cmd 19

[Project Root]
F:\WKDIR\CodeComposer\EEA_SA_V613b\BOOT\TEST

[build options]
3
Linker = "-a -r -c -f 0x00000000 -heap 0x2000 -m pdi.map -o pdi.out -stack 0x07BF -x "
Assembler = "-lx -v30 -mrb -iF:\WKDIR\CodeComposer\EEA_SA_V613b\BOOT\SOURCE -iF:\WKDIR\CodeComposer\EEA_SA_V613b\BOOT\SOURCE\INCLUDE -iF:\WKDIR\CodeComposer\EEA_SA_V613b\INCLUDE "
Compiler = "-gks -v33 -pl -mbfr -alsx -x1 -frF:\WKDIR\CodeComposer\EEA_SA_V613b\BOOT\OBJ -fsF:\WKDIR\CodeComposer\EEA_SA_V613b\BOOT\SOURCE\ASM -iF:\WKDIR\CodeComposer\EEA_SA_V613b\BOOT\SOURCE -iF:\WKDIR\CodeComposer\EEA_SA_V613b\BOOT\SOURCE\INCLUDE -iF:\WKDIR\CodeCom "

[source files]
..\SOURCE\ISR.c 1173731918 1
..\SOURCE\MAIN.c 1486139873 1
..\SOURCE\SERIAL.c 1173731918 1
..\SOURCE\TIMER.c 1173731918 1
..\SOURCE\MODBUSRTU.c 1173731918 1
..\..\LIB\pdi.lib 0 1
..\SOURCE\BUFFER.c 1173731918 1
..\..\LIB\FLASH.c 1327946670 1
..\SOURCE\boot.asm 1173731918 1
..\SOURCE\LCD.c 1439584385 1
GLBLS.H 1486141724 0
BRANCH.H 1173731918 0
ETC.H 0 0
BUFFER.H 1173731918 0
PERIPH.H 0 0
FLASH.H 0 0
SERIAL.H 1173731918 0
MODBUSRTU.H 1173731918 0
I2C.H 0 0
-1250

[dependencies]
 2 10:9 11:10 -12391
 1 10:12 -12303
 2 10:11 16:12 -77
 1 10:11 -32007
 2 10:11 17:12 -1128
 0 -802
 2 10:11 13:12 -30500
 2 10:21 15:22 -31970
 0 -802
 2 10:11 18:12 -2075
 7 12:14 13:15 14:16 15:17 16:18 17:19 18:20 32074
 0 -802
 0 -802
 0 -802
 0 -802
 0 -802
 0 -802
 0 -802
 0 -802

[version]
2.0
*/
-a -r -c -f 0x00000000 -heap 0x2000 -m pdi.map -o pdi.out -stack 0x07BF -x
"..\OBJ\LCD.obj"
"..\SOURCE\boot.obj"
"..\OBJ\FLASH.obj"
"..\OBJ\BUFFER.obj"
"..\OBJ\MODBUSRTU.obj"
"..\OBJ\TIMER.obj"
"..\OBJ\SERIAL.obj"
"..\OBJ\MAIN.obj"
"..\OBJ\ISR.obj"
"..\..\LIB\pdi.lib"
"..\SOURCE\pdi.cmd"
/******** End of Project Data Generated by Code Composer ********/
