REG_STREAM_SELECT
REG_NUM_SAMP
REG_SALINITY
REG_TEMPERATURE_USER_ADJUST
REG_LOCK[2]
REG_LOCK[3]
REG_LOWSALT_THRESHOLD
REG_OIL_ADJ
REG_OIL_ADJ
REG_WATERCUT_ALARM_LO
REG_WATER_INDEX
REG_FREQ_WATER_LO
REG_FREQ_WATER_HI
REG_OIL_INDEX
REG_FREQ_OIL_LO
REG_FREQ_OIL_HI
OIL_P1
OIL_P0
REG_CAL_OIL
REG_CAL_WATER
PORTCFG[MSVE.tmpi[0]].PREFIX
PORTCFG[MSVE.tmpi[0]].SUFFIX
PORTCFG[MSVE.tmpi[0]].NETWDOG
PORTCFG[MSVE.tmpi[0]].Retry_Time
PORTCFG[MSVE.tmpi[0]].Slave_ID
Density_D3
Density_D2
Density_D1
Density_D0
COR[0].damp_flow_rate
COR[0].damp_density
FC[n].density
FC[n].salinity
FC[n].watercut
FC[n].pressure
FC[n].T
FC[n].FLOW_TOTAL
FC[n].density_water
FC[n].density_waterST
FC[n].density_oil
FC[n].density_oilST
FC[n].Shrinkage
FC[0].Meter_Factor
